# Jupyter Notebook: тетрадка в ячейку <a id='intro'></a>

Jupyter Notebook — помощник аналитика и специалиста по Data Science.

Тетради Юпитера состоят из ячеек двух типов:
* с кодом на Python,
* с текстом на языке разметки Markdown.

Это делает тетради удобными для анализа данных. Аналитики исследуют данные, чтобы ответить на вопросы бизнеса. Ячейки с кодом нужны им для обработки данных, а ячейки с текстом — чтобы объяснить ход и результаты исследования.

Этот текст вы читаете в текстовой ячейке. А следующая ячейка содержит код:

In [5]:
print('У технарей тетради в клетку,')
print('у гуманитариев — в линейку,')
print('у аналитиков — в ячейку.')

first_number = 2
second_number = 3

result = first_number + second_number

print('first_number + second_number =', result)

У технарей тетради в клетку,
у гуманитариев — в линейку,
у аналитиков — в ячейку.
first_number + second_number = 5

Кликните на ячейку с кодом один раз. Вокруг неё появится зелёная рамка. Это режим редактирования. В этом режиме вы можете  менять и запускать код.

Чтобы запустить код, нажмите `Shift+Enter` или кликните ▶| Run в верхнем меню.

## Ячейки с кодом

Результат выполнения кода отображается прямо под ним. Причём результат последнего выражения в ячейке сразу выводится на экран — для него не нужно вызывать `print()`. Запустите следующую ячейку, чтобы в этом убедиться.

In [2]:
def sum_square(x, y):
    return x*x + y*y;

sum_square(first_number, second_number) # здесь можно не использовать print()

13

Код вывел на экран `13` и без функции `print()`.

Здесь заметна и другая деталь. В коде мы не объявили переменные `first_number` и `second_number`. Но функция исполнилась без ошибок. Она получила значения переменных из прошлой ячейки. 

Выполняя код в ячейках, Юпитер запоминает результат. Все изменения в переменных будут учтены при следующем вызове любой ячейки.

Запускать ячейки можно в любом порядке. Это удобно для экспериментов. Когда эксперименты завершены, проверьте, как ячейки работают вместе. Для этого в меню выберите Cell. Вы увидите три команды:
* Run All запустит все ячейки.
* Run All Above — ячейки от первой до выбранной.
* Run All Below — от выбранной и до конца тетради.

Чтобы сбросить все изменения в переменных, кликните ⟳ в верхнем меню.

**Задание**. Заполните пропуск в следующей ячейке так, чтобы после выполнения кода значение переменной `sum_result` стало равным `8`. Проверьте решение — запустите ячейку.

In [3]:
third_number = 2 # заполните пропуск
sum_result = sum_square(third_number, first_number)
sum_result # последним выражением в ячейке может быть просто имя переменной

8

Вновь последнее значение из кода, `sum_result` автоматически выводится на экран.

In [6]:
first_number = 1
print(first_number)

last_number = 2
last_number

1

2

Как вы могли заметить, в предыдущей ячейке мы использовали `print()` для вывода переменной `first_number`, а для `last_number` -- нет. Ниже расскажем о правилах вывода разных объектов в Jupyter Notebook.

## Вывод одного объекта в одной ячейке

Нужно вывести одну таблицу (датафрейм DataFrame) или один столбец (объект Series) в одной ячейке — укажите имя объекта в последней строке ячейки. Тогда для красивого вывода вам не понадобятся функции вывода:

In [7]:
import pandas as pd

# пример
df = pd.read_csv('/datasets/yandex_music_project.csv')
df

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
...,...,...,...,...,...,...,...
65074,729CBB09,My Name,McLean,rnb,Moscow,13:32:28,Wednesday
65075,D08D4A55,Maybe One Day (feat. Black Spade),Blu & Exile,hip,Saint-Petersburg,10:00:00,Monday
65076,C5E3A0D5,Jalopiina,NaN,industrial,Moscow,20:09:26,Friday
65077,321D0506,Freight Train,Chas McDevitt,rock,Moscow,21:43:59,Friday
65078,3A64EF84,Tell Me Sweet Little Lies,Monica Lopez,country,Moscow,21:59:46,Friday

In [8]:
# ещё пример
df = pd.read_csv('/datasets/yandex_music_project.csv')
df.head()

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday

In [9]:
# и ещё один
df = pd.read_csv('/datasets/yandex_music_project.csv')
# столбец всегда выводится текстом
df['Track']

0                        Kamigata To Boots
1              Delayed Because of Accident
2                        Funiculì funiculà
3                    Dragons in the Sunset
4                              Soul People
                       ...
65074                              My Name
65075    Maybe One Day (feat. Black Spade)
65076                            Jalopiina
65077                        Freight Train
65078            Tell Me Sweet Little Lies
Name: Track, Length: 65079, dtype: object

То же самое справедливо для вывода одного числа или одной строки:

In [10]:
# пример ячейки
platform = 'Яндекс Практикум'
platform

'Яндекс Практикум'

In [11]:
# ещё пример
b = 777
b

777

В последней строке ячейки можно вывести один объект. И часто используется правило: одна ячейка — один вывод.

## Вывод нескольких таблиц или столбцов в одной ячейке

Иногда требуется вывести более одной таблицы (или более одного столбца) в одной ячейке. Редко, но бывает. Используйте функцию `display()` — её можно применять во всех строках ячейки, кроме последней. В последней строке укажите имя объекта — таблицы или столбца.

In [12]:
# пример ячейки
first_df = pd.read_csv('/datasets/yandex_music_project.csv')
display(first_df)
second_df = pd.read_csv('/datasets/yandex_music_project.csv')
second_df

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
...,...,...,...,...,...,...,...
65074,729CBB09,My Name,McLean,rnb,Moscow,13:32:28,Wednesday
65075,D08D4A55,Maybe One Day (feat. Black Spade),Blu & Exile,hip,Saint-Petersburg,10:00:00,Monday
65076,C5E3A0D5,Jalopiina,NaN,industrial,Moscow,20:09:26,Friday
65077,321D0506,Freight Train,Chas McDevitt,rock,Moscow,21:43:59,Friday
65078,3A64EF84,Tell Me Sweet Little Lies,Monica Lopez,country,Moscow,21:59:46,Friday

,userID,Track,artist,genre,City,time,Day
0,FFB692EC,Kamigata To Boots,The Mass Missile,rock,Saint-Petersburg,20:28:33,Wednesday
1,55204538,Delayed Because of Accident,Andreas Rönnberg,rock,Moscow,14:07:09,Friday
2,20EC38,Funiculì funiculà,Mario Lanza,pop,Saint-Petersburg,20:58:07,Wednesday
3,A3DD03C9,Dragons in the Sunset,Fire + Ice,folk,Saint-Petersburg,08:37:09,Monday
4,E2DC1FAE,Soul People,Space Echo,dance,Moscow,08:34:34,Monday
...,...,...,...,...,...,...,...
65074,729CBB09,My Name,McLean,rnb,Moscow,13:32:28,Wednesday
65075,D08D4A55,Maybe One Day (feat. Black Spade),Blu & Exile,hip,Saint-Petersburg,10:00:00,Monday
65076,C5E3A0D5,Jalopiina,NaN,industrial,Moscow,20:09:26,Friday
65077,321D0506,Freight Train,Chas McDevitt,rock,Moscow,21:43:59,Friday
65078,3A64EF84,Tell Me Sweet Little Lies,Monica Lopez,country,Moscow,21:59:46,Friday

## Вывод нескольких строк или чисел в одной ячейке

Чтобы вывести более одной строки (или более одного числа) в одной ячейке, используйте функцию `print()`. Она пригодится для вывода нескольких простых объектов.

Для вывода нескольких простых объектов воспользуйтесь функцией `print()`:

In [13]:
# пример ячейки
a = 100
b = 777
print('Сейчас будут выведены числа...')
# будут выведены значения a и b
print(a)
print(b)
print('Вывод закончен.')

Сейчас будут выведены числа...
100
777
Вывод закончен.

Чтобы вывести значение в последней строке ячейки, `print()` можно не использовать:

In [ ]:
# пример ячейки
a = 100
b = 777
print('Сейчас будут выведены числа...')
# будут выведены значения a и b
print(a)
b

Jupyter Notebook используют не только для исследований, но и для презентации результатов. Поэтому красивое форматирование таблиц повышает ценность проекта.

##  Ячейки с текстом

Текстовые ячейки нужны, чтобы отображать текст вместе с элементами форматирования. Например, с заголовками, списками или таблицами.

Любую ячейку с кодом можно превратить в текстовую — и наоборот. 

Измените тип следующей ячейки на текстовый и примените форматирование. Для этого: 
* кликните по ячейке таблицей,
* выберите в меню Cell -> Cell type -> Markdown;
* нажмите `Shift + Enter`, чтобы отформатировать ячейку.


### Таблица 1

| Язык                     | Доля сайтов в топ 10 млн | Носители, млн | Говорящие, млн |
|--------------------------|-----------------|--------------------|-------------|
| Английский               | 53.90%          | 378.2              | 1121        |
| Русский                  | 6.10%           | 153.9              | 264.3       |
| Немецкий                 | 6.00%           | 76                 | 132         |
| Испанский                | 4.90%           | 442.3              | 512.9       |
| Французский              | 4.00%           | 76.7               | 284.9       |
| Японский                 | 3.40%           | 128.2              | 128.3       |
| Португальский            | 2.90%           | 222.7              | 236.5       |
| Итальянский              | 2.40%           | 64.8               | 67.8        |
| Персидский               | 2.00%           | 60                 | 110         |
| Польский                 | 1.80%           | 39.6               | 40.3        |
| Китайский | 1.70%           | 908.7              | 1.107       |
| Датский                  | 1.20%           | 22                 | 28          |
| Турецкий                 | 1.20%           | 78.5               | 78.9        |
| Чешский                  | 1.00%           | 10.4               | 10.6        |

Текстовые ячейки размечают по правилам Markdown. В текст добавляют специальные символы, которые подсказывают Юпитеру, как должен быть отформатирован текст. Специальные символы не видны, пока вы не войдёте в режим редактирования. 

**Режимы ячейки**

Когда вы кликаете по текстовой ячейке один раз, вокруг неё появляется синяя рамка. Это командный режим: в нём можно изменить тип ячейки, но не её содержимое.

Кликните по текстовой ячейке дважды, чтобы открыть её в режиме редактирования. Форматирование исчезнет, а вы увидите специальные символы.

**Жирный текст** помещают между двумя звёздочками, `**`.

Дважды кликните по этой ячейке, чтобы увидеть текст с разметкой Markdown. 

Затем нажмите `Shift + Enter` — чтобы вернуть форматирование.

**Списки** начинают со знака `-` или `*`:

- пришёл,
- увидел,
- проанализировал.

**Выделить код** в тексте можно, поместив его в косые кавычки. Например: `display()`. 

Несколько строчек кода помещают в тройные обратные кавычки — как в следующей ячейке.

**Заголовки** начинают со знака `#`:

```
# Заголовок первого уровня
## Заголовок второго уровня
### Заголовок третьего уровня
```

Дважды кликните на любой заголовок в этом документе, чтобы посмотреть его разметку. И верните форматирование с помощью `Shift + Enter`.

**Ссылки** в маркдауне состоят из двух частей:
* в квадратных скобках пишут текст, который увидит пользователь;
* за ними в круглых скобках — ссылку, которую Юпитер добавит к тексту. 

Например:

Маркдаун — `[Яндекс Практикум](https://practicum.yandex.ru/)`.

Результат — [Яндекс Практикум](https://practicum.yandex.ru/).


**Внутренние ссылки** ведут к отдельным ячейкам тетради. Это пригодится в самостоятельных проектах. С помощью внутренних ссылок в Юпитере создают оглавление исследования.

Чтобы сослаться на ячейку тетради, к ней добавляют метку с id — уникальным именем метки:

`<a id='intro'></a>`

Такую метку мы добавили в первую ячейку этой тетради. Теперь можно написать ссылку, которая вернёт в начало этой тетрадки: 

Маркдаун — `[Начало тетрадки](#intro)`.

Результат — [начало тетрадки](#intro).

## Сочетания клавиш
Сочетания клавиш помогают быстро вызывать некоторые команды. Например, вы видели, как действует сочетание `Shift + Enter`:

* в ячейке с кодом — выполняет код;
* в ячейке с текстом — форматирует текст.

Это сочетание клавиш работает как в режиме редактирования, так и в режиме управления.

Другие горячие клавиши работают только в режиме управления, когда ячейка обведена синей рамкой:

- `m`  — из ячейки с кодом делает текстовую; 
- `y`  — из текстовой ячейки делает ячейку с кодом;
- `b`  — добавляет новую ячейку под выбранной;
- `a`  — добавляет новую ячейку над выбранной.

Наконец, в режиме редактирования нажмите `Esc`, чтобы перейти в режим управления.

Поэкспериментируйте с сочетаниями клавиш в этом документе. Например, выберите эту ячейку, создайте под ней новую — клавишей `b`. Затем сделайте её текстовой — клавишей `m`.


### Лайфхак: как запомнить горячие клавиши
* останавливайте себя, когда тянетесь к кнопке меню,
* вспомните, какое сочетание клавиш может заменить кнопку, к которой вы тянулись,
* нажмите эту горячую клавишу.

Это полезная привычка, которая ещё сохранит вам время.


## Автоматическое сохранение тетради
Юпитер сам сохраняет изменения в тетради. Но иногда автоматическое сохранение даёт сбой. В самостоятельных проектах после значимых изменений сохраните файл — нажмите на иконку дискеты, 💾. В верхнем меню она расположена слева.